### ISSUE TITLE
Where do you put the require?

### ISSUE THREAD

**Issue by erikmellum** [hakovala/atom-watcher#5]
It's not clear to me where I need to put the require code. Does it go in the main process js, or the renderer? I tried both and got an error about document not being defined in each case.

**Comment by hakovala** [comment]
You need to put the require code to the renderer code.
Where you would do DOM manipulation etc., usually the js file that is loaded from HTML script tag.

Here's a snippet that I use most of the time:

```
// might be good idea to wait for all dom content to load before loading 'atom-watcher', not 100% sure though..
document.addEventListener('DOMContentLoaded', function() {
  // some code

  // try-catch so that atom-watcher can be easily omitted
  try { require('atom-watcher')(); } catch (e) {} 

// more code
};
```

Hopefully this helps..

I have to add a clearer example in the readme.. :) When I have time..
